[project]
name = "openai-realtimeapidemopythonpc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyaudio>=0.2.14",
    "pysocks>=1.7.1",
    "websocket-client>=1.9.0",
]
